services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      WEBHOOK_URL: http://localhost:5678/
      N8N_HOST: n8n.pcpsaude.com.br
      GENERIC_TIMEZONE: America/Sao_Paulo
      N8N_LOG_LEVEL: debug
      N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE: true
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "5678:5678"

volumes:
  n8n_data: