services:
  waha:
    image: devlikeapro/waha
    env_file:
      - .env
    ports:
      - "3003:3000"
    volumes:
      - waha_sessions:/app/.sessions
      - waha_media:/app/.media

volumes:
  waha_sessions:
  waha_media: